export default {
    viewAll: {
        id: 'all',
        flag: 0,
        alias: '现有',
        type: 'viewAll',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'circle-o',
        iconStyleSuffix1: '',
        kindness: '显示现有的文本',
    },
    viewHot: {
        id: 'hot',
        flag: 0,
        alias: '热络',
        type: 'viewHot',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'heart',
        iconStyleSuffix1: '',
        kindness: '显示热文本',
    },
    viewCold: {
        id: 'cold',
        flag: 0,
        alias: '渐冷',
        type: 'viewCold',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'heart-o',
        iconStyleSuffix1: '',
        kindness: '显示冷文本',
    },
    init: {
        flag: 0,
        type: 'init',
        iconStyleSuffix: 'sticky-note-o',
        iconStyleSuffix0: 'sticky-note-o',
        iconStyleSuffix1: '',
        kindness: '我是勤劳的便签',
    },
    allHot: {
        flag: 0,
        type: 'allHot',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'hand-rock-o',
        iconStyleSuffix1: '',
        kindness: '全部变热',
    },
    allCold: {
        flag: 0,
        type: 'allCold',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'hand-paper-o',
        iconStyleSuffix1: '',
        kindness: '全部变冷',
    },
    addTodo: {
        flag: 0,
        type: 'addTodo',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'pencil-square-o',
        iconStyleSuffix1: '',
        kindness: '添加了一条文本',
    },
    deleteTodo: {
        flag: 0,
        type: 'deleteTodo',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'trash-o',
        iconStyleSuffix1: '',
        kindness: '删除了一条文本',
    },
    toggleTodo: {
        flag: 0,
        type: 'toggleTodo',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'toggle-on',
        iconStyleSuffix1: 'toggle-off',
        kindness: '切换了一条文本',
    },
    toggleHeat: {
        flag: 0,
        type: 'toggleHeat',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'toggle-on',
        iconStyleSuffix1: 'toggle-off',
        kindness: '切换了一条文本',
    },
    hotItem: {
        flag: 0,
        type: 'hotHeat',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'toggle-on',
        iconStyleSuffix1: '',
        kindness: '温暖了一条文本',
    },
    coldItem: {
        flag: 0,
        type: 'coldHeat',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'toggle-off',
        iconStyleSuffix1: '',
        kindness: '冷藏了一条文本',
    },
    toggleAll: {
        flag: 0,
        type: 'toggleAll',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'toggle-on fa-lg',
        iconStyleSuffix1: 'toggle-off fa-lg',
        kindness: '切换了全部文本',
    },
    clearCompleted: {
        flag: 0,
        type: 'clearCompleted',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'trash',
        iconStyleSuffix1: '',
        kindness: '删除了冰凉的文本',
    },
    test: {
        flag: 0,
        type: 'test',
        iconStyleSuffix: '',
        iconStyleSuffix0: 'try',
        iconStyleSuffix1: '',
        kindness: '测试中　。。。',
    },
};